version: 2
jobs:
  build:
    working_directory: ~/pantheon-systems/wp_launch_check
    parallelism: 1
    docker:
    - image: circleci/php:7.1
    steps:
    - checkout
    - run: echo 'No tests to run'
